{{
    config(
        materialized    = 'table',
        tags            = ['attr', 'warehouse'],
)
}}

select 
TO_DATE(DATE, 'DD/MM/YYYY') DATE,
TO_DATE(MONTH_START, 'DD/MM/YYYY') MONTH_START,
TOTAL,
PIXOBLE_FREEAPP,
VALUE_LEAF_FREEAPP as ValueLeaf_freeapp,
FACEBOOK_INTERNAL_FREEAPP as FacebookInternal_freeapp, 
THE_FLUENCER_FREEAPP as TheFluencer_freeapp, 
XAI_FREEAPP,
F_2_C_BANNER_MIGRATION_FREEAPP as F2C_Banner_Migration_freeApp,
STAN_FREEAPP,
GOOGLE_ADS_INTERNAL_FREEAPP as GoogleAdsInternal_freeapp, 
ORGANIC_FREEAPP,
PIXOBLE_CASHAPP,
VALUE_LEAF_CASHAPP as ValueLeaf_Cashapp, 
FACEBOOK_INTERNAL_CASHAPP as FacebookInternal_Cashapp, 
THE_FLUENCER_CASHAPP as TheFluencer_Cashapp, 
XAI_CASHAPP,
F_2_C_BANNER_MIGRATION_CASH_APP as F2C_Banner_Migration_CashApp,
STAN_CASHAPP,
GOOGLE_ADS_INTERNAL_CASHAPP as GoogleAdsInternal_Cashapp,
ORGANIC_CASHAPP,
UNICORN_TRIVIA_FACEBOOK_LAGUNA_AD_ACCOUNT,
MIGRATION_SOLITAIRE_CASHAPP,
ORGANIC_SOLITAIRE_FREEAPP,
MIGRATION_SOLITAIRE_FREEAPP,
ORGANIC_SOLITAIRE_CASHAPP,
UNICORN_MOB_RUN_FACEBOOK_LAGUNA_AD_ACCOUNT,
UNICORN_BUMPER_CORNS_FACEBOOK_LAGUNA_AD_ACCOUNT
from 
google_sheets.input_la_attr_source_spends
